[project]
name = "crewai-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=1.7.2",
    "crewai-tools>=1.7.2",
]
